services:
  # Web Service - API Principal
  - type: web
    name: bts-blocktrust
    env: python
    plan: starter
    region: oregon
    buildCommand: bash build.sh
    startCommand: cd backend && gunicorn app:app --bind 0.0.0.0:$PORT --timeout 120
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: SENDGRID_API_KEY
        sync: false
      - key: TOOLBLOX_MINT_IDENTITY_URL
        value: "https://api.toolblox.net/run/0xbea959B61f62608eDDd40e1eB8888a42cfc573Ef"
      - key: TOOLBLOX_REGISTER_SIGNATURE_URL
        value: "https://api.toolblox.net/run/0xbb3862Ac621aaD9B54FE9C9884608e0F9991F772"
      - key: TOOLBLOX_VERIFY_URL
        value: "https://api.toolblox.net/run/0x5103f409300C5D2FBd746A9D96B5110cc3b599d2"
      - key: TOOLBLOX_NETWORK
        value: "polygon"
      - key: ALERT_WEBHOOK_URL
        sync: false
      - key: SUMSUB_APP_TOKEN
        value: "prd:ePc2R1JUrZwuzplYhv3cwfzJ.UZt9oGTKYbcfA2HNvJevEZBMxymYN754"
      - key: SUMSUB_SECRET_KEY
        value: "dTgJiI6lFnAXeR2mu4WixaMxrKcn9ggY"
      - key: SUMSUB_LEVEL_NAME
        value: "basic-kyc"
      - key: SMTP_HOST
        value: "smtp.gmail.com"
      - key: SMTP_PORT
        value: "587"
      - key: SMTP_USER
        value: "vinicius.debian@btsglobalcorp.com"
      - key: SMTP_PASS
        sync: false
      - key: SMTP_FROM
        value: "vinicius.debian@btsglobalcorp.com"
      - key: PORT
        value: "10000"
      - key: NETWORK
        sync: false
      - key: POLYGON_RPC_URL
        sync: false
      - key: DEPLOYER_PRIVATE_KEY
        sync: false
      - key: IDENTITY_NFT_ADDRESS
        sync: false
      - key: PROOF_REGISTRY_ADDRESS
        sync: false
      - key: FAILSAFE_ADDRESS
        sync: false
      - key: MOCK_MODE
        value: "false"
      - key: SLO_LATENCY_MS
        value: "800"
      - key: SLO_UPTIME_TARGET
        value: "99.5"

  # Background Worker - Blockchain Event Listener
  - type: worker
    name: bts-blocktrust-listener
    env: python
    plan: starter
    region: oregon
    buildCommand: bash build.sh
    startCommand: cd backend && python3 listener.py
    envVars:
      - key: DATABASE_URL
        fromService:
          name: bts-blocktrust
          type: web
          envVarKey: DATABASE_URL
      - key: POLYGON_RPC_URL
        fromService:
          name: bts-blocktrust
          type: web
          envVarKey: POLYGON_RPC_URL
      - key: LISTENER_POLL_INTERVAL
        value: "15"

  # Background Worker - System Monitor
  - type: worker
    name: bts-blocktrust-monitor
    env: python
    plan: starter
    region: oregon
    buildCommand: bash build.sh
    startCommand: cd backend && python3 -m monitor.runner
    envVars:
      - key: DATABASE_URL
        fromService:
          name: bts-blocktrust
          type: web
          envVarKey: DATABASE_URL
      - key: MONITOR_CHECK_INTERVAL
        value: "60"
      - key: SLO_UPTIME_TARGET
        fromService:
          name: bts-blocktrust
          type: web
          envVarKey: SLO_UPTIME_TARGET
      - key: SLO_LATENCY_MS
        fromService:
          name: bts-blocktrust
          type: web
          envVarKey: SLO_LATENCY_MS
      - key: ALERT_WEBHOOK_URL
        fromService:
          name: bts-blocktrust
          type: web
          envVarKey: ALERT_WEBHOOK_URL

