services:
  - type: web
    name: bts-blocktrust
    env: python
    plan: starter
    region: oregon
    buildCommand: bash build.sh
    startCommand: cd backend && python app.py
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: SENDGRID_API_KEY
        sync: false
      - key: TOOLBLOX_MINT_IDENTITY_URL
        value: "https://api.toolblox.net/run/0xbea959B61f62608eDDd40e1eB8888a42cfc573Ef"
      - key: TOOLBLOX_REGISTER_SIGNATURE_URL
        value: "https://api.toolblox.net/run/0xbb3862Ac621aaD9B54FE9C9884608e0F9991F772"
      - key: TOOLBLOX_VERIFY_URL
        value: "https://api.toolblox.net/run/0x5103f409300C5D2FBd746A9D96B5110cc3b599d2"
      - key: TOOLBLOX_NETWORK
        value: "polygon"
      - key: ALERT_WEBHOOK_URL
        sync: false
      - key: SUMSUB_APP_TOKEN
        value: "uKBKq1VVgbptORChz3E1RtDB.FuhXzSuDD7eTyQe7WuekjAkDbuyl9Fw"
      - key: SUMSUB_SECRET_KEY
        value: "HPuMPbrCSs1dgobgDRIVJu5JP82eLgFc"
      - key: SUMSUB_LEVEL_NAME
        value: "basic-kyc-level"
      - key: SMTP_HOST
        value: "smtp.gmail.com"
      - key: SMTP_PORT
        value: "587"
      - key: SMTP_USER
        value: "vinicius.debian@btsglobalcorp.com"
      - key: SMTP_PASS
        sync: false
      - key: SMTP_FROM
        value: "vinicius.debian@btsglobalcorp.com"
      - key: PORT
        value: "10000"

