services:
  - type: web
    name: bts-blocktrust
    env: python
    plan: starter
    region: oregon
    buildCommand: |
      cd frontend && pnpm install && pnpm build
      cd ../backend && pip install -r requirements.txt
    startCommand: cd backend && python app.py
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: SENDGRID_API_KEY
        sync: false
      - key: TOOLBLOX_MINT_IDENTITY_URL
        value: "https://api.toolblox.net/run/0xbea959B61f62608eDDd40e1eB8888a42cfc573Ef"
      - key: TOOLBLOX_REGISTER_SIGNATURE_URL
        value: "https://api.toolblox.net/run/0xbb3862Ac621aaD9B54FE9C9884608e0F9991F772"
      - key: TOOLBLOX_VERIFY_URL
        value: "https://api.toolblox.net/run/0x5103f409300C5D2FBd746A9D96B5110cc3b599d2"
      - key: TOOLBLOX_NETWORK
        value: "amoy"
      - key: ALERT_WEBHOOK_URL
        sync: false
      - key: SUMSUB_APP_TOKEN
        value: "uKBKq1VVgbptORChz3E1RtDB.FuhXsZsUDD7eTyQe7WueKjAkDbuyJ9Fw"
      - key: SUMSUB_SECRET_KEY
        value: "HPuMPbFC5s1dgqbgDRIVJu5JP82eLgFc"
      - key: PORT
        value: "10000"

